#!/bin/sh
set -euf

##
# pip-install-favorites
#
# Use the `pip` command to install our favorite packages.
#
# ## Tracking
#
# * Command: https://github.com/sixarm/brew-install-favorites-for-developing
# * Version: 6.0.0
# * Created: 2020-06-20T22:56:18Z
# * Updated: 2022-07-29T18:43:43Z
# * License: GPL-2.0-or-later or contact us for custom
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

# altgraph: Graph (network) package.
pip install altgraph

# awscli: Amazon Web Services (AWS) command line interface (CIL).
pip install awscli

# aws-shell: Amazon Web Services (AWS) shell for interactive commands.
pip install aws-shell

# awsebcli: Amazon Web Services (AWS) Elastic Beanstalk (EB) command line interface (CLI).
pip install awsebcli

# bdist-mpkg: Create virtualenv built distributions.
pip install bdist-mpkg

# beautifulsoup: Website screen-scraping and messy parsing.
pip install beautifulsoup4

# boto: Amazon Web Services API interfaces for Python 2
pip install boto

# boto3: Amazon Web Services API interfaces for Python 3
pip install boto3

# celery: Task queues to distribute work across resources.
pip install celery

# cffi: C-code Foreign Function Interface.
pip install cffi

# click: Create command line interfaces in a composable way.
pip install click

# construct: Declarative parser (and builder) for binary data.
pip install construct

# cryptography: Cryptography recipes and primitives.
pip install cryptography

# cycler: Composable style cycles.
pip install cycler

# dataset: Easy-to-use data handling for SQL data stores.
pip install dataset

# dicttoxml: Convert a Python dictionary or other native data type into a valid XML string.
pip install dicttoxml

# dill: A better "pickle" to serialize objects to disk.
pip install dill

# enum34: Python 3.4 Enum backported.
pip install enum34

# flask: Flask is a lightweight WSGI web application framework.
pip install flask

# flask-login: Flask-Login provides user session management for Flask.
pip install flask-login

# flask-sqlalchemy: Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy.
pip install flask-sqlalchemy

# folium: Visualize geographic data.
pip install folium

# funcsigs: Function signatures
pip install funcsigs

# git-filter-repo: Git tool to filter repo files, better than git filter-branch.
pip install git-filter-repo

# idna: Support for the Internationalised Domain Names in Applications (IDNA) protocol.
pip install idna

# ipaddress: IPv4/IPv6 manipulation library.
pip install ipaddress

# jc: JSON converter for popular Unix commands.
pip install jc

# joblib: Job library for caching, parallelizing, persistence.
pip install joblib

# lxml: XML parsing (prefer this when you need speed).
pip install lxml

# macholib: Mach-O header analysis and editing.
pip install macholib

# marshmallow: Simplified object serialization.
pip install marshmallow

# matplotlib: Math plotting library.
pip install matplotlib

# mock: mock is a library for testing in Python.
pip install mock

# modulegraph: modulegraph determines a dependency graph between Python modules.
pip install modulegraph

# ndg-httpsclient: A HTTPS client implementation.
pip install ndg-httpsclient

# nose: nose extends the test loading and running features of unittest.
pip install nose

# numpy: NumPy scientific computing with data structures.
pip install numpy

# pandas: Data analysis, time series, and statistics.
pip install pandas

# passlib: Passlib is a password hashing library.
pip install passlib

# pbr: Python Build Reasonableness.
pip install pbr

# pip: Python package manager.
pip install pip

# pelican: Pelican static site generator.
pip install pelican

# pomp: Web scraping (prefer vs. scrapy).
pip install pomp

# pillow: Friendly fork of PIL, the Python Imaging Library (https://python-pillow.org/).
pip install pillow

# progressbar2: Progress bar (prefer tqdm).
pip install progressbar2

# psutil: psutil provides process and system utilities.
pip install psutil

# pudb: Python debugger (prefer vs. pdb).
pip install pudb

# pyasn1: Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208).
pip install pyasn1

# pycparser: pycparser is a complete parser of the C language.
pip install pycparser

# pygithub: Python GitHub API.
pip install pygithub

# pyjwt: pyjwt is a Python implementation of Java Web Tokens as per RFC 7519.
pip install pyjwt

# pymysql: Python bindings for MySQL.
pip install pymysql

# pyopenssl: High-level wrapper around a subset of the OpenSSL library.
pip install pyopenssl

# py2app: py2app is a Python setuptools command which will allow you to make standalone code for macOS.
pip install py2app

# pyparsing: PyParsing is a Python parsing module
pip install pyparsing

# pytest: The pytest framework makes it easy to write tests.
pip install pytest

# python-dateutil: dateutil provides powerful extensions to datetime
pip install python-dateutil

# python-magic: python-magic is a Python interface to the libmagic file type identification library.
pip install python-magic

# pytz: pytz brings the Olson timezone database into Python.
pip install pytz

# redis: The Python interface to the Redis key-value store.
pip install redis

# requests: Requests is HTTP for Humans (http://www.python-requests.org/).
pip install requests

# rich: rich text and beautiful formatting in the terminal.
pip install rich

# schema: Simple data validation library (prefer vs. voluptuous).
pip install schema

# schematics: Data structures and transformations.
pip install schematics

# scipi: SciPy library of algorithms and mathematical tools.
pip install scipy

# scrapy: Scrape and extract data from websites (https://scrapy.org/) (prefer pomp).
pip install scrapy

# semgrep: Semantic grep for source code quality evaluation
pip install semgrep

# setuptools: setup tools
pip install setuptools

# six: Six is a Python 2 and 3 compatibility library.
pip install six

# sphinx: Sphinx makes it easy to create intelligent and beautiful documentation.
pip install sphinx

# sphinx-rtd-theme: Sphinx "Read The Docs" theme.
pip install sphinx-rtd-theme

# sqlalchemy: SQL database abstraction library.
pip install sqlalchemy

# tinydb: Pure Python NoSQL database.
pip install tinydb

# Twisted: event-driven networking engine (https://twistedmatrix.com/).
pip install Twisted

# tqdm: Display progress bars for loops in code (prefer vs. progressbar2).
pip install tqdm

# virtualenv: Virtual environments for independent installations.
pip install virtualenv

# visidata: Rapidly explore columnar data in the terminal.
pip install visidata

# voluptuous: Data validation library (prefer schema).
pip install voluptuous

# xattr: xattr interacts with extended attributes extend the basic attributes of files and directories in the file system.
pip install xattr

# xlrd: Excel reader to export spreadsheet data
pip install xlrd

# zope: Zope is an open-source web application server.
pip install zope
